### ISSUE TITLE
Readthedocs uses Sphinx 3.1.0 and experimental functions and classes show incorrect signature

### ISSUE THREAD

**Issue by harupy** [optuna/optuna#1353]
### Example

![Screen Shot 2020-06-11 at 10 32 03](https://user-images.githubusercontent.com/17039389/84335134-1d842180-abcf-11ea-88e5-3693e95d91eb.png)

https://optuna.readthedocs.io/en/latest/reference/visualization.html#optuna.visualization.plot_param_importances

---

### Log on Readthedocs

![Screen Shot 2020-06-11 at 10 44 57](https://user-images.githubusercontent.com/17039389/84335783-9df75200-abd0-11ea-9ce6-334ef5386c71.png)

https://readthedocs.org/projects/optuna/builds/11227856/

---

### How to fix

Fix `docs/requirements.txt` should solve this issue.

**Comment by harupy** [comment]
https://github.com/sphinx-doc/sphinx/pull/7651 introduced in Sphinx 3.1.0 seems to cause this bug.

**Comment by harupy** [comment]
There are two ways to prevent this issue in the future.

1. Use this `docs/requirements.txt` file in CircleCI.
2. Remove `docs/requirements.txt` and use `.readthedocs.yml` to install dependencies with `setup.py`.

```yml
...
python:
   version: 3.7
   install:
      - method: pip
         path: .
         extra_requirements:
             - document

# This config is equivalent to `pip install .[document]`
```

- https://docs.readthedocs.io/en/stable/config-file/v2.html#python
- https://docs.readthedocs.io/en/stable/config-file/v2.html#packages
